// <auto-generated />
using EFCore.Inheritance.TablePerHierarchy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Inheritance.TablePerHierarchy.Migrations
{
    [DbContext(typeof(TablePerHierarchyDbContext))]
    [Migration("20220815081646_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCore.Inheritance.TablePerHierarchy.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<short>("Discriminator")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasDiscriminator<short>("Discriminator");
                });

            modelBuilder.Entity("EFCore.Inheritance.TablePerHierarchy.Models.EFBlog", b =>
                {
                    b.HasBaseType("EFCore.Inheritance.TablePerHierarchy.Models.Blog");

                    b.HasDiscriminator().HasValue((short)1);
                });

            modelBuilder.Entity("EFCore.Inheritance.TablePerHierarchy.Models.RssBlog", b =>
                {
                    b.HasBaseType("EFCore.Inheritance.TablePerHierarchy.Models.Blog");

                    b.HasDiscriminator().HasValue((short)2);
                });
#pragma warning restore 612, 618
        }
    }
}
